spring:
  application:
    name: kunefe-

server:
  port: 8080

grpc:
  server:
    port: 6565

kunefe:
  data:
    dir: ./kunefe-data
  offset:
    dir: ./kunefe-offsets
  log:
    segment:
      max-bytes: 67108864         # 64MB
      max-hours: 168              # 7 days
    retention:
      hours: 168                  # 7 days
      check-interval-ms: 300000   # 5 minutes

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    dev.selimsahin.kunefe: DEBUG